spes: Unset NEED_AIDL_NDK_PLATFORM_BACKEND
* Conflicts with hardware_lineage_compat.

  Error: system/hardware/interfaces/keystore2/aidl/Android.bp:19:1: module "android.system.keystore2-V1-ndk_platform"
  already defined by hardware/lineage/compat/Android.bp:196:1 <-- previous definition here.

Change-Id: I8cf23de7c8a37952fbc24495b25b9ca488115dac
Signed-off-by: Kajal4414 <81718060+Kajal4414@users.noreply.github.com>